### PR TITLE
Added Turkish Support

### PR DESCRIPTION
**Pull request by CidQu**

### CODE REVIEW

**Comment by WSSDude** [comment]
Sorry for not replying, was thinking about this for a bit...

I dont know if I want to include translations I dont understand fully tbh, mainly when localization system is just 99% copy-pasted from other project I work on and it will get updated for sure as that project and this updates (in other words, big chance localization files will need arbitrary updates)

I also expect more strings to be included as more things are included.

Guess I'll think about this a bit more... There is fallback system in place so I guess worst thing that could happen and I would not be able to update are the new strings, so new strings would be displayed in English 🤔 

But I know of at least few shortcomings with current localization system in place - I use only Latin glyphs currently (so Korean for example won't work). Although I'm solving this in the other mentioned project so this won't be issue for that long I hope...

You also have to manually replace the current font in the case of lets say mentioned Korean, even when glyphs ranges are correct. Also getting this solved in the other project currently.

There are also quite a few limitations placed by ImGui being used (no RTL, ligatures, diacritical chars etc. ImGui is quite limited in this regard).

Localization is quite tricky as I found out lately, partially thanks to your enthusiasm and me starting overthinking things a bit 😁 

In any case, will think about it as mentioned.

**Comment by CidQu** [comment]
I just made this PR because I can. Nothing big to worry about, you can close it 👀. I have one question tho. How can I use your tool to extract Hitman 3: World Assasination sound files? 

The game is using WWES(SoundWise) I have tool to convert this file type to .ogg but can't import back to game.

I can open Issue on GitHub with example files if you want. We really want to localize this game to Turkish.

**Comment by WSSDude** [comment]
This works only with older Glacier 1 games, not the new ones.

Games that came after Kane & Lynch 2 (which is Hitman: Sniper Challenge and newer) would need completely different approach. Both FMOD and WWise are whole another beasts which I dont plan to tackle here.

**Comment by WSSDude** [comment]
I also never really looked that deep into them so I can't point you to anything relevant. Not something that is public at least... One guy I know made a tool that allowed us to do a voice over for Outlast, but I believe it was pretty targeted towards whichever specific version of WWise that game used and was not open source or published, anywhere :/

**Comment by CidQu** [comment]
Okay, thank you so much! I'm closing this PR.

**Pull request closed without merging**
